---
####### head node play ############
- name: Head node Scheduler configuration
  vars_files: group_vars/cluster_params.yml
  become: yes
  hosts: head
  connection: local
  tags: head_node_play
  roles: 
    - slurm-user
    - slurm-rpm-build
    - head-node_munge_key
    - slurmdbd


####### compute node play ########
- name: Compute node Scheduler configuration
  vars_files: group_vars/cluster_params.yml
  become: yes
  hosts: all_nodes
  tags: compute_node_play
  roles:
    - slurm-user
    - compute-node_munge_key
    - slurmd
