---
### Head node play
- name: Build mpi package and install on the local host
  hosts: head 
  vars_files: group_vars/openmpi.yml
  connection: local
  gather_facts: no

  roles:
   - openmpi-rpm-build  
   - openmpi-rpm-install_head_node

### compute nodes play
- name: Install openmpi on compute nodes 
  hosts: all_nodes
  vars_files: group_vars/openmpi.yml

  roles: 
   - openmpi-rpm-install_compute_nodes
