- name: Checking to see if the pmix SRC RPM exists 
  ansible.builtin.stat:
    path: roles/pmix-rpm-build/files/pmix-{{ pmix_release }}.src.rpm
  register: file_srcrpm

- name: If it does not exist, download it 
  ansible.builtin.command:
    cmd: wget https://github.com/openpmix/openpmix/releases/download/v{{ pmix_release }}/pmix-{{ pmix_release }}-1.src.rpm -P roles/slurm-rpm-build/files
  when: not file_srcrpm.stat.exists

- name: Checking to see if the pmix rpm have already been created
  ansible.builtin.stat:
    path: /tmp/rpmbuild/RPMS/x86_64/pmix-{{ pmix_release }}-1.el8.x86_64.rpm
  register: file_rpm

- name: Building pmix rpms, this will skip if they are already built
  ansible.builtin.command:
    cmd: rpmbuild --define "_topdir /tmp/rpmbuild" --rebuild -ta roles/slurm-rpm-build/files/pmix-{{ pmix_release }}-1.src.rpm 
  when: not file_rpm.stat.exists

- name: Install RPM on the head node
  ansible.builtin.dnf:
    disable_gpg_check: yes
    name: "/tmp/rpmbuild/RPMS/x86_64/pmix-{{ pmix_release }}-1.el8.x86_64.rpm"
    state: present
