---
- name: create MPI user on the head 
  hosts: head
  connection: local
  gather_facts: no
  tasks:

    - name: Create MPI user
      ansible.builtin.user: 
        name: mpiuser
        password: '*'
        uid: 5000
        state: present
        shell: /bin/bash
        createhome: yes
        home: /head/NFS/mpiuser
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        ssh_key_passphrase: 

- name: create MPI user on the nodes
  hosts: all_nodes
  gather_facts: no
  tasks:

    - name: Create MPI user
      ansible.builtin.user:
        name: mpiuser
        password: '*'
        uid: 5000
        state: present
        shell: /bin/bash
        createhome: no
        home: /head/NFS/mpiuser
        generate_ssh_key: no

