############## Compute node play ###############################
- name: Remove compute node host-based SSH configuration
  hosts: all_nodes
  gather_facts: no
  tasks:

     - name: Remove sshd scripts for host based authentication
       ansible.builtin.file:
         path: "{{ item }}"
         state: absent 
       with_items:
         - /etc/ssh/ssh_config.d/ssh_lci.conf'
         - /etc/ssh/sshd_config.d/sshd_lci.conf
         - /etc/ssh/ssh_known_hosts
         - /etc/hosts.equiv
         - /tmp/.ansible_rocky
         - /tmp/.ansible_root
       ignore_errors: True
       tags: rm_comp

     - name: Remove host_based auth content in sshd_config 
       ansible.builtin.blockinfile: 
         path: /etc/ssh/sshd_config 
         marker: "# {mark} ANSIBLE MANAGED BLOCK" 
         block: ""

     - name: Restart SSH service on the nodes
       ansible.builtin.service:
         name: sshd
         state: reloaded

############## Head node play ##################################
- name: Head node SSH host-based client removal 
  hosts: head
  gather_facts: no 
  tasks: 

    - name: delete scripts for host based authentication
      ansible.builtin.file:
        path: "{{ item }}" 
        state: absent
      with_items:
        - /etc/ssh/ssh_config.d/ssh_lci.conf
        - /etc/ssh/ssh_known_hosts
      become: true
      ignore_errors: True
      tags: rm_head

